version: '3'
services:
  web:
    working_dir: /mailers
    build: .
    volumes:
      - "./:/mailers"
    command: "bin/rails s puma -b '0.0.0.0' -p 3000"
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db:db
  db:
    image: postgres:9.6
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - "./.data/postgres:/var/lib/postgresql/data"
